export const API_KEY = 'AIzaSyBiEsx3WO2mffI3zcnDj07In4gRYn7mJ9Y';
export const AUTH_DOMAIN = 'bookfinder-7cf67.firebaseapp.com';
export const DB_URL = 'https://bookfinder-7cf67.firebaseio.com';
export const PROJECT_ID = 'bookfinder-7cf67';
export const STORAGE_BUCKET = 'bookfinder-7cf67.appspot.com';


export const faculties = [
    "Agraria",
    "Architettura",
    "Beni Culturali",
    "Biologia e Biotecnologia",
    "Chimica",
    "DAMS",
    "Economia e Finanza",
    "Farmacia",
    "Fisica",
    "Fisioterapia",
    "Giurisprudenza",
    "Infermieristica",
    "Informatica",
    "Ingegneria",
    "Lettere e Filosofia",
    "Lingue e Letterature Straniere",
    "Matematica",
    "Medicina",
    "Psicologia",
    "Scienze della Comunicazione",
    "Scienze Motorie",
    "Scienze Politiche",
    "Scienze della Formazione",
    "Sociologia",
    "Storia",
    "Veterinaria",
];

export const universities = [
   'Università degli Studi di Roma "La Sapienza"',
   'Università di Bologna',
   'Università degli Studi di Napoli Federico II',
   'Università degli Studi di Torino',
   'Università degli Studi di Milano',
   'Università degli Studi di Padova',
   'Università degli Studi di Firenze',
   'Politecnico di Milano',
   'Università di Pisa',
   'Università degli Studi di Bari Aldo Moro',
   'Università degli Studi di Catania',
   'Università degli Studi di Palermo',
   'Università Cattolica del Sacro Cuore',
   'Università degli Studi di Salerno',
   'Università degli Studi di Milano-Bicocca',
   'Politecnico di Torino',
   'Università degli Studi Roma Tre',
   'Università degli Studi di Genova',
   'Università degli Studi di Roma Tor Vergata',
   'Università della Calabria',
   'Università degli Studi di Cagliari',
   'Università degli Studi di Parma',
   'Università degli Studi della Campania Luigi Vanvitelli',
   'Università degli Studi "Gabriele d\'Annunzio"',
   'Università degli Studi di Modena e Reggio Emilia',
   'Università degli Studi di Verona',
   'Università degli Studi di Perugia',
   'Università degli Studi "Niccolò Cusano"',
   'Università degli Studi di Messina',
   'Università degli Studi di Pavia',
   'Università Ca\' Foscari Venezia',
   'Università degli Studi di Ferrara',
   'Università degli Studi di Bergamo',
   'Università del Salento',
   'Università degli Studi di Trento',
   'Università degli Studi dell\'Aquila',
   'Università degli Studi di Siena',
   'Università Politecnica delle Marche',
   'Università degli Studi di Udine',
   'Università degli Studi di Trieste',
   'Università degli Studi di Urbino "Carlo Bo"',
   'Università degli Studi di Brescia',
   'Università commerciale Luigi Bocconi',
   'Università degli Studi di Sassari',
   'Università degli Studi del Piemonte Orientale Amedeo Avogadro',
   'Università degli Studi di Napoli "Parthenope"',
   'Università degli Studi di Napoli "L\'Orientale"',
   'Università degli Studi dell\'Insubria',
   'Università degli Studi di Foggia',
   'Università degli Studi di Macerata',
   'Politecnico di Bari',
   'Libera università di lingue e comunicazione IULM',
   'Università Vita-Salute San Raffaele',
];

